#spring.application.name=eureka-client
#eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka/
#
#

spring:
  application:
    name: eureka-client

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: false
    hostname: test.abc.com
    instanceId: ${eureka.instance.hostname}

logging:
  level:
    com.netflix.discovery: DEBUG

